# Generated by Django 4.1.7 on 2023-12-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='car_images')),
                ('price', models.FloatField()),
            ],
        ),
    ]
